### ISSUE TITLE
[feature] source maps

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#114]
should probs have those using exorcist and a separate method to serve em

**Comment by mantoni** [comment]
I found it super easy to work with [convert-source-map](https://www.npmjs.com/package/convert-source-map) – looking at the dependencies, that seems to be what everybody else does as well *haha*.

Here is an example of how I used it: https://github.com/mantoni/source-mapper.js/blob/cbe89de3f7b68ff422fb9809cbf3cb6ef4b22862/lib/source-mapper.js#L17

**Comment by yoshuawuyts** [comment]
We have source maps now! :grin:
