### ISSUE TITLE
browserify shorthands don't work from the cli

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#115]
```sh
# doesn't work
$ bankai --js [ -t brfs ] index.js

# this does
$ bankai --js [ --transform brfs ] index.js
```
we probs need to preparse the arguments and expand them - quite sure we can copy the aliases from the browserify code since it's v v stable - probs also need to do this for `sheetify`

**Comment by runeh** [comment]
There's an extra complication here, as some of the command line options don't map directly to stuff in the config object passed to browserify. Case in point:

Using `-g`, or even the unshorthanded `--global-transform` wont work even if doing preparsing.
The `-g` option isn't propagated into browserify via a separate option. It uses the same option as `-t` internally, but the transform entry takes a `global: true` prop. See https://github.com/substack/node-browserify/blob/master/bin/args.js#L197

For this to work in bankai, i suspect it would have to reproduce some of the same logic.

Might be possible to require https://github.com/substack/node-browserify/blob/master/bin/args.js#L197 and use that to instanciate the browserify instance instead. Not sure if that is meant to be part of the public browserify API though.

I could probably take a crack at this, but need to know if it's the right direction before putting too much time into it.

**Comment by yoshuawuyts** [comment]
yeah I think copying those lines would be good; probably place that as a
separate file in /lib/parse-browserify-arguments.js or something

**Comment by goto-bus-stop** [comment]
v9 doesn't take Browserify options on the CLI at all anymore so I think this can be closed
