### ISSUE TITLE
options to watchify

### ISSUE THREAD

**Issue by forresto** [choojs/bankai#129]
I want to plug in https://github.com/traducer/browserify-livereload but don't see an easy way to get options to watchify.

**Comment by kasperlewau** [comment]
```sh
$ bankai -j [ --plugin browserify-livereload ]
```

switching out the usual `-p` flag for `--plugin` made it "work" on my end. 

as far as passing subargs through to the plugin itself, I'm out of luck with this: 

```sh
$ bankai -j [ --plugin [ browserify-livereload --outfile=tmp.js ] ]
```

browserify cannot find the plugin `[object Object]`.

should work for a simple no-opt transform/plugin though.

**Comment by yoshuawuyts** [comment]
Yeah, we should alias the -p and -t flags to --plugin and --transform
respectively. The browserify JS API fails to understand them. Patch would
be very welcome!

**Comment by goto-bus-stop** [comment]
closing since we don't have cli args anymore in v9. #359 is about using custom plugins in v9. thanks & happy new year! 🎆
