### ISSUE TITLE
Better handle ES6 source

### ISSUE THREAD

**Issue by s3ththompson** [choojs/bankai#171]
### Expected behavior
`bankai start`, `bankai build`, and `bankai inspect` work with ES6, or produce actionable error messages.

### Actual behavior
When handling ES6 source, `bankai start` fails with:
```
SyntaxError: Invalid assignment while parsing file: /Users/seththompson/code/readrc/viewer/test/index.js
    at JS_Parse_Error.get (eval at <anonymous> (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
```
`bankai build` fails with:
```
11:23:12 🚨  bankai Invalid assignment while parsing file: /Users/seththompson/code/readrc/viewer/test/index.js
```
and `bankai inspect` fails with:
```
TypeError: Cannot read property 'apply' of undefined
    at Stream.method [as destroy] (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/duplexer/index.js:47:38)
    at /Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:43:45
    at call (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:50:3)
    at Array.forEach (native)
    at /Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:70:25
    at f (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/once/once.js:25:25)
    at PassThrough.<anonymous> (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/pump/index.js:29:21)
    at PassThrough.f (/Users/seththompson/.homebrew/lib/node_modules/bankai/node_modules/once/once.js:25:25)
    at emitOne (events.js:96:13)
    at PassThrough.emit (events.js:191:7)
```

### Steps to reproduce behavior
Use bankai on files with ES6 source, for example an `index.js`:
```js
const choo = require('choo')
const html = require('choo/html')

var app = choo();
app.route('/', (state, emit) => {
  return html`<body><h1>Hello World</h1></body>`
})
app.mount('body')
```

**Comment by YerkoPalma** [comment]
This is because of [uglify](https://github.com/yoshuawuyts/bankai#uglify-toggle)

> Uglify only supports JavaScript syntax up to ES5. If you want to use later syntax you'll need to either disable the uglifyify transform with `--uglify=false` or add a compiler to convert your ES5+ syntax down to ES5

**Comment by s3ththompson** [comment]
Yeah, I traced this to uglify, it just seems that Bankai should have better error messages if it's going to enable uglify by default.

My app broke upgrading to 7.5.0 and it took me a while to figure it out.

Also, [disc](https://github.com/hughsk/disc/issues/51) doesn't handle ES6+ either, so you might want to note that.

**Comment by yoshuawuyts** [comment]
> Yeah, I traced this to uglify, it just seems that Bankai should have better error messages if it's going to enable uglify by default.

I'm open for better error messages. Right now I have no idea how other people are using Bankai, and where it breaks down. I'm all ears for feedback; PR very welcome here!

---

> Also, disc doesn't handle ES6+ either

It unpacks the bundle that browserify gives it, there shouldn't be any parsing going on outside of browserify. Not sure what the root cause is tho, but yeah I hope this will help you somewhat on your way.

**Comment by s3ththompson** [comment]
Will try to submit a PR this evening.

**Comment by joshgillies** [comment]
Just to note, I was hitting this issue until I realised the key browserify is expecting is `--transform` as opposed to just `-t` as mentioned in the `bankai` docs.

The following works for me without having to disable uglify:
```sh
bankai build -j [ --transform es2020 ] index.js
```

**Comment by toddself** [comment]
@joshgillies: i don't want to transcode down to es5 just for uglify when my runtime supports es6.

**Comment by yoshuawuyts** [comment]
@toddself The uglifyjs version bump should take care of this I think; patch would still be very welcome! :sparkles:

**Comment by goto-bus-stop** [comment]
bankai 9 uses the latest uglify with support for ES6. please reopen or create a new issue if a similar problem occurs!
