### ISSUE TITLE
Wrong path resolution on building

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/bankai#198]
I have a project structured like this 

```text
project/
├── api/
├── public/
├── src/
└── server.js
```

My `api` folder has my backend, and my `src` folder my frontend source, in my `public` folder is my _compiled_ frontend. I can serve my frontend stuff with `bankai start`, but I can't use it to build my stuff. If I run:

```bash
$ bankai build --assets=assets src/index.js public/
```

I get an error saying that the folder `src/public/assets` is not found. If I run 

```bash
$ bankai build --assets=assets src/index.js ../public/
```

I get my assets build in my public folder, and a new public folder _outside_ of my root project folder with my html, js and css files.

What is happening, is that for building html, js and css, bankai is taking as root the current folder, but when copying assets, it uses as root the entry file folder. If your entry point is in your root directory this would never be an issue, if you use a structure like the one I show (or like what express or other full stack frameworks do) it will have this behaviour.

**Comment by yoshuawuyts** [comment]
Oh oops, that's no good - I think it might be time to add some tests to
this. Tho a standalone patch just to fix this would also be very welcome.
Thanks!

**Comment by YerkoPalma** [comment]
haha haven't realized that there is no tests :smile: 

The correct behaviour would be that this command

```bash
$ bankai build --assets=assets src/index.js public/
```

would put everything in the `public/` folder right?

**Comment by yoshuawuyts** [comment]
Yep, that's it!

**Comment by goto-bus-stop** [comment]
I don't believe this applies anymore as of v9. thanks!
