### ISSUE TITLE
TLS certs during dev

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#204]
https://github.com/davewasmer/devcert - allows us to ship http2 in the future too ✨

**Comment by toddself** [comment]
Not only just for HTTP2 -- we use secure only cookies and have to jump through a few hoops to verify that don't send them in test or dev and it's a huge pain in the rear!

I would be happy work on a PR for this

**Comment by yoshuawuyts** [comment]
That'd be sweet! :D

**Comment by toddself** [comment]
See #206

**Comment by goto-bus-stop** [comment]
seems addressed in v9. thanks!
