### ISSUE TITLE
How to pass environment variables to bankai build?

### ISSUE THREAD

**Issue by lenaten** [choojs/bankai#215]
I know about envify plugin, but can't make it work with bankai build command.

**Comment by toddself** [comment]
@lenaten what have you tried so far?  Can you show some examples? 

We are using envify and bankai in our dev environment with no issues.

**Comment by toddself** [comment]
The following example works:

index.js
```js
console.log(process.env.HELLO_WORLD
```

```
bankai start index.js -j [ -t envify ]
```

I have bankai installed globally (`npm i -g bankai`) and envify installed locally (`npm i envify`)

**Comment by lenaten** [comment]
For some reason I had bankai V5 (maybe because I copied from some old start guide).
Your command works great in the latest version

Thanks!
