### ISSUE TITLE
Using --html=false and --css=false from cli

### ISSUE THREAD

**Issue by nilliams** [choojs/bankai#220]
`--html=false` and `--css=false` don't appear to be usable from the cli (with `bankai build`).

 * `--html=false` does not error, but `index.html` is still output into outdir.

```
> bankai build client/index.js public/ --html=false

14:18:18 ✨  bankai public/bundle.js 6.7KB
14:18:18 ✨  bankai public/bundle.css 8B
14:18:18 ✨  bankai public/index.html
```

 * `--css=false` errors like so:

```
> bankai build client/index.js public/ --css=false

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Cannot find module 'false' from '/path/to/my-choo-proj'
```

(Tried without the `=` too). Is this intended to work, or is there some other way to disable HTML and CSS processing?

**EDIT:** Could be related to #160.

**Comment by yoshuawuyts** [comment]
Yeah, it might be related to that - tbh not sure if we should allow disabling parsing from the CLI tho. Imho, I kinda feel we should have a better story for JS usage and forward people to just run it from there C:

**Comment by goto-bus-stop** [comment]
think this no longer applies now that v9 is out. thanks!
