### ISSUE TITLE
double body exists in HTML

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#222]
Even though the browser parses it right, we're sending two body elements

<img width="1280" alt="screen shot 2017-07-24 at 01 48 19" src="https://user-images.githubusercontent.com/2467194/28504167-41d5b748-7012-11e7-9a12-a4cd91104db1.png">

**Comment by f-mer** [comment]
Tracked this one down to [here](https://github.com/choojs/bankai/blob/7c14057f506a413e23ffdc7d1283f49f39f81351/index.js#L182). The server-rendered html contains a `body` element and is inserted into the body element through [trumpet](https://github.com/substack/node-trumpet). Seems like a replace could work but trumpet doesn't support that anymore. Don't know where to go from here ¯\_(ツ)_/¯

**Comment by yoshuawuyts** [comment]
My guess is we should probably update trumpet to support it. Another option
would be to write a body deduper, but that's like really hacky haha. We
need to rewrite a good amount of our HTML stack in bankai anyway; started
work on that here https://github.com/stackhtml/documentify

**Comment by YerkoPalma** [comment]
documentify is supposed to be a better version of create-html?

**Comment by yoshuawuyts** [comment]
Haha, I wouldn't say it's better - it's _different_ and can be configured
through package.json the way browserify and sheetify can. That's the main
appeal tbh (:

**Comment by YerkoPalma** [comment]
haha yeah that was what I meant :D

**Comment by goto-bus-stop** [comment]
fixed in v9 🎉
