### ISSUE TITLE
Bankai just says `error iterating over files` with no more details

### ISSUE THREAD

**Issue by passcod** [choojs/bankai#223]
I created an app with `create-choo-app`, made a few changes, and at some point I apparently made a mistake, but I couldn't debug what I did because `bankai build` gave me very quiet output, and `bankai serve` just stalled on the first request silently.

```
$ npm start

> cogitare@1.0.0 start /home/code/js/cogitare
> bankai start index.js

19:25:44 ✨  bankai bundle:js
19:25:44 ✨  bankai Started for index.js on http://localhost:8080
[ stall forever ]
```

```
$ npm run build
20:43:01 ✨  bankai assets/icon.png done
20:43:01 ✨  bankai assets/icon.svg done
20:43:01 ✨  bankai assets/bulma.css done
20:43:01 🚨  bankai error iterating over files
```

Now, `-V` does reveal some useful stuff, but wouldn't it be better to output a stack trace or at least the error message instead of stalling/erroring (almost) silently by default? It's… not helpful.

**Comment by yoshuawuyts** [comment]
Uh oh, that's no good - if you run --verbose it'll tell you more (:

**Comment by passcod** [comment]
Ah, see my edits :) I realised this afterwards, but the almost-silent-by-default behaviour seems... not nice. Lots of frustration trying to figure out what's wrong with no _obvious_ feedback.

**Comment by yoshuawuyts** [comment]
Yeah, fully with you; so sorry this happened. I really want to improve
error handling in bankai; already started on a rewrite. I think we did a
good job in https://github.com/choojs/create-choo-app; having the same
level of quality for bankai would be 💯 I think

**Comment by YerkoPalma** [comment]
Is this still an issue in Banka@9?

**Comment by yoshuawuyts** [comment]
@YerkoPalma This should be fixed in Bankai 9, yeah.

@passcod let us know if you're still experiencing any issues. Closing for now!
