### ISSUE TITLE
Don't crash

### ISSUE THREAD

**Issue by bcomnes** [choojs/bankai#229]
When developing, if you have a bad import or anything else wrong with your code, bankai crashes.  

We should make it so bankai itself doesn't crash when users make an error.

**Comment by marcbachmann** [comment]
Webpack is doing this pretty nice. They send the error to the client and show it in the console.
Maybe we could integrate error log support to [choo-reload](https://github.com/choojs/choo-reload).

**Comment by bcomnes** [comment]
Yosh said this would be fixed in the new version.

**Comment by goto-bus-stop** [comment]
Yeah AFAIK this is fixed
