### ISSUE TITLE
SSR is very agressive!

### ISSUE THREAD

**Issue by toddself** [choojs/bankai#234]
Trying to upgrade to 9, and I've got some code that talks to `window.localStorage` that only runs in the browser, but bankai 9 is trying to run this on the server.

I don't need/want to install `global/window` here since this code will only ever run on the client (it's part of the app wrapper we use) -- are we going to require all code that uses `window` or `document` or another browser-only object to properly shim it for node?

**Comment by yoshuawuyts** [comment]
This still an issue? Greenkeeper shouldn't have pinged to update to this
one, given it shouldn't be marked as "stable" :(

**Comment by mcollina** [comment]
I stumbled into this as well ;)

**Comment by yoshuawuyts** [comment]
The versioning issue should be fixed now. Agree with the sentiment that SSR should be a gentle improvement, not fail loudly if it doesn't work - think new branch should take care of that! :D
