### ISSUE TITLE
new-new-new ExperimentalWarning: The http2 module is an experimental API.

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#238]
Does bankai#new-new-new have a way of turning off the http2 experiement?

**Comment by YerkoPalma** [comment]
Not sure if we are talking the same here, but I get this error because of http2
![image](https://user-images.githubusercontent.com/5105812/30325553-98e6c922-979b-11e7-8c0a-d5d9a3d35447.png)
using node 8.4.0

**Comment by shotlom** [comment]
Interesting - yeah I'm using node v8.4 also.

**Comment by yoshuawuyts** [comment]
uh oh 😅 - yeah, maybe we should leave http2 for what it is for a little
bit. I'll ask James when it's projected to be stable so we can remove the
flag and do away with all errors ( the code already accounts for it not
being available otherwise). Sorryyyyyy :D

**Comment by shotlom** [comment]
seems to work now in node v.8.5, but I can't access site on my dev machine via localhost due to insecure https :)

**Comment by knoxcard** [comment]
Node 8.7 seems to work, Node 8.8 produces this error for me.

**Comment by shotlom** [comment]
Cross Ref #313
