### ISSUE TITLE
Failed to load sw.js 

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#243]
With the new build folder structure the service-workerjs file is located in a hashed subfolder as shown in the image below. 

![image](https://user-images.githubusercontent.com/398402/30672130-ee1f1df4-9ead-11e7-8d07-fe53f6a1e342.png)

However it appears that the ```choo-service-worker``` service:

```javascript
  app.use(require('choo-service-worker')())
```
is looking for /sw.js at the root of the dist directory.

![image](https://user-images.githubusercontent.com/398402/30672191-40c6c9ee-9eae-11e7-94df-0e3be8d5198c.png)

**Comment by yoshuawuyts** [comment]
I think the right way to approach this is to remember if there's a `service-worker.js` file or a `sw.js` file, and output the right one. I kinda changed my mind, and like `service-worker` better, so we might change it up in `choo-service-worker` at some point, but both approaches should be equally valid for bankai. Good catch! :D

**Comment by yoshuawuyts** [comment]
Fixed in 633112e :grin:

**Comment by shotlom** [comment]
I've just updated  github:choojs/bankai#new-new-new. 

When building the sw.js in the dist folder you get: 

```javascript
URLS = ["/", "/bundle.css", "/bundle.js", "assets/icon.png"];
```
However none of these will exist in the ```./dist``` folder due to the hashing, and so the sw.js returns an error (see image below).

Also, I think having ./sw.js at the root without hashing means you lose cache busting, which is important for pushing new releases of service workers to the client.  

![image](https://user-images.githubusercontent.com/398402/30729202-35dc7170-9fa1-11e7-94f4-114e5bd27cb9.png)

**Comment by shotlom** [comment]
So my ```./dist``` directory now looks like:

![image](https://user-images.githubusercontent.com/398402/30729280-ce926488-9fa1-11e7-8c81-9e08d8ca8e1a.png)

**Comment by yoshuawuyts** [comment]
@shotlom Looks like you have an outdated SW config. We're now injecting vars as globals. Totally forgot to document it tho, so doing that now!

For now here's what you can use instead:
```js
/* global self */

var VERSION = String(Date.now())
var FILES = process.env.FILE_LIST

// Respond with cached resources
self.addEventListener('fetch', function (e) {
  var request = self.caches.match(e.request)
    .then(function (req) {
      return req || self.fetch(e.request)
    })

  e.respondWith(request)
})

// Register worker
self.addEventListener('install', function (e) {
  var cacheFiles = self.caches.open(VERSION)
    .then(function (cache) {
      return cache.addAll(FILES)
    })

  e.waitUntil(cacheFiles)
})

// Remove outdated resources
self.addEventListener('activate', function (e) {
  var removeKeys = self.caches.keys()
    .then(function (keyList) {
      return Promise.all(keyList.map(function (key, i) {
        if (keyList[i] !== VERSION) return self.caches.delete(keyList[i])
      }))
    })

  e.waitUntil(removeKeys)
})
```

Also don't worry about those extra files, they're just compressed versions so they can be served straight from nginx / caddy. Hope it makes sense! :tada:

**Comment by shotlom** [comment]
Ok, yes, that seems to be working when i run the bankai server.

When i do ```npm run build``` I'm not getting a sw.js link in ***index.html***. 

So when I run a local server out of the box I get a lighthouse audit which looks like this:

![image](https://user-images.githubusercontent.com/398402/30745477-b0d9aa76-9fe9-11e7-97b6-935ced75c11c.png)

**Comment by shotlom** [comment]
So I think this is a question about running build and about cache busting for a build - are you going to do cache busting (hashing) for the ```npm run build``` output?

**Comment by shotlom** [comment]
Ohhhhhhhhhhhh, so, hold on ....

after a build,

```
var FILES = process.env.FILE_LIST
```

results in 

```
FILES = ["/scripts/e39490bd7501f76a/bundle.js", "/styles/f45e2938cc8b9aad/bundle.css", "assets/icon.png", "assets/icon0.png", "assets/icon1.png", "/", "/:", "/manifest.json"];
```

oooooooh. That's so cool! Nice one!

But we still need the link in index.html, and another question, are all those assets also supposed to be inserted into /manifest.json? 

Because as it is only icon.png seems to transfer to the manifest.
