### ISSUE TITLE
sw.js FILES have scripts and styles directories

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#244]
So with the new way of injecting files into the sw.js

```
var FILES = process.env.FILE_LIST
```

The result in the build sw is,

 FILES = ["/**scripts**/5c315ddfa14e2ba1/bundle.js", "/**styles**/f45e2938cc8b9aad/bundle.css", "assets/icon.png", "/", "/:", "/manifest.json"];
 
however the scripts and styles folders don't exist in the build directory. So FILES should be:

```
 FILES = ["/5c315ddfa14e2ba1/bundle.js", "/f45e2938cc8b9aad/bundle.css", "assets/icon.png", "/", "/:", "/manifest.json"];
```

**Comment by shotlom** [comment]
here is the result of a build

![image](https://user-images.githubusercontent.com/398402/30771248-fecd4c78-a085-11e7-8c07-05f9487503e0.png)

**Comment by yoshuawuyts** [comment]
Great for catching; fixed! :grin:
