### ISSUE TITLE
Static assets not served with correct MIME type

### ISSUE THREAD

**Issue by s3ththompson** [choojs/bankai#249]
Previous versions of Bankai used [`send`](https://www.npmjs.com/package/send) to serve static assets with the correct mimetype.

Currently the code https://github.com/choojs/bankai/blob/master/http.js#L160 just sends the raw buffer.

**Comment by yoshuawuyts** [comment]
Yeah, we oughta fix this. Related to this, we should also not hold the files in a buffer, but rather only hold the routes to the files. This would massively speed up file serving too, and prevent Bankai from running out of memory.

**Comment by yoshuawuyts** [comment]
This should be solved by #260 :D

**Comment by goto-bus-stop** [comment]
going to assume #260 fixed it, since it's using `send` now—pls reopen if not
