### ISSUE TITLE
Server render swallows errors

### ISSUE THREAD

**Issue by s3ththompson** [choojs/bankai#255]
This one took a little while to figure out :P

[This try/catch block](https://github.com/choojs/bankai/blob/master/lib/server-render.js#L28) effectively swallows any errors in server-side rendering your app (thus causing only the index to be rendered). Is there any reason that we don't want to print out these errors? Is `proxyrequire` noisy/flaky?

Once I manually dumped the error, it turned out that none of my routes were rendering because I was including a library that assumed the existence of `window.document`.

> Side note: It seems as though the `proxyrequire` library doesn't work with `node --inspect`... Whenever I had a DevTools window open for debugging, Bankai ran forever, stuck somewhere in the build process. This made setting breakpoints mostly impossible. Are there any `proxyrequire` alternatives?

**Comment by yoshuawuyts** [comment]
I think logging it out makes sense; reason I didn't do it initially is
because it flooded everything with warnings and was tricky to figure out.
If we could apply the tty-error to this that'd be amazing!
