### ISSUE TITLE
Theme color isn't derived correctly

### ISSUE THREAD

**Issue by f-mer** [choojs/bankai#263]
The theme color is derived from the `color`-property in the `manifest.json`which isn't specified.
I suggest the `theme_color`-property should be used to set the content of the `theme-color` meta-tag.

**Comment by yoshuawuyts** [comment]
Which theme color property are you referring to? You're right it should be
derived correctly.

**Comment by f-mer** [comment]
I'm referring to the line in [graph-manifest.js](https://github.com/choojs/bankai/blob/master/lib/graph-manifest.js#L55) where the `color`-property is read. Shouldn't it use the `theme_color`-property instead of `color`?
