### ISSUE TITLE
Subresource integrity

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#269]
In order to make code more secure, it'd be neat if we could implement sub resource integrity checks on all our script and image tags. Probably needs investigating how to add it for `polyfill.io` / whitelist it.

## Refs
- https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity

**Comment by jbergstroem** [comment]
> @yoshuawuyts said:
>  Probably needs investigating how to add it for polyfill.io / whitelist it.

That's going to be tricky seeing how it changes per user-agent. It likely has to be omitted [for polyfill].

**Comment by yoshuawuyts** [comment]
Yeah, agree.

So something I'd like to try out at some point is create a both a babel and
a non-babel build — then try and load the non-babel build with `<script
type=module>`, and if the browser doesn't support ES modules they can load
the build using `<script nomodule>`. That way evergreen browsers get the
fast, optimized build (and we can assume they support Fetch,
Object.Assign() and other stuff)`, and other browsers can safely rely on
builds with fallbacks for these. Which in turn opens up the ability to use
subresource integrity.

Does this make sense? :D

**Comment by yoshuawuyts** [comment]
Closed by #301 :tada:
