### ISSUE TITLE
Support Koa for full-stack apps

### ISSUE THREAD

**Issue by cjhowe7** [choojs/bankai#271]
Currently [Koa doesn't support bypassing response handling](http://koajs.com/#ctx-res), meaning that `bankai/http` in the beta won't work with Koa. It would be nice if we supported promises, or found some other way to support Koa.

**Comment by yoshuawuyts** [comment]
I think what you can do with `koa` is intercept the request before it hits the frameworks, like so:
```js
var bankai = require('bankai/http')
var http = require('http')
var koa = require('koa')

var app = koa()
var handler = koa.callback()
var compiler = bankai('index.js')

var server = http.createServer(function (req, res) {
  compiler(req, res, function () {
    handler(req, res)
  })
})

server.listen(8080)
```
This isn't great, but imo it definitely beats supporting a custom package.

**Comment by yoshuawuyts** [comment]
@cjhowe7 does this make sense? Can we close this?

**Comment by cjhowe7** [comment]
Ah, yes! Thanks!
