### ISSUE TITLE
Bankai + Nanocomponent + ES6 Class Syntax Example

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#272]
Could you please do a full example, end-to-end, using ES6 Class Syntax with bankai@9.0.0-rc2 ?

I'm having trouble using "import" when importing an ES6 nanocomponent.

**Comment by yoshuawuyts** [comment]
We don't support import at the moment - browserify doesn't support it yet,
so we don't either. We might add this for dynamic import at some point, but
that isn't the case yet

**Comment by shotlom** [comment]
Huh! Ok so that's why I'm getting the error! :) There I was thinking it was doing something stupid. So browserify is the limiting dependency ...
