### ISSUE TITLE
Parsing Errors in Acorn with v9 (not in v8)

### ISSUE THREAD

**Issue by AutoSponge** [choojs/bankai#287]
```bash
scripts:browserify.bundle Unexpected token (8:60) SyntaxError: Unexpected token (8:60)     
at Parser.pp$4.raise (/Users/paul/GitHub/books/node_modules/acorn/dist/acorn.js:2610:13)     
at Parser.pp.unexpected (/Users/paul/GitHub/books/node_modules/acorn/dist/acorn.js:637:8)     
at Parser.pp.semicolon (/Users/paul/GitHub/books/node_modules/acorn/dist/acorn.js:614:64)     
at Parser.pp$1.parseExpressionStatement (/Users/paul/GitHub/books/node_modules/acorn/dist/acorn.js
```

I kept getting this error. When I didn't get this error, I got the message in the browser that I had no routes (there's only one `/*` route). Going back to v8 fixed this issue.

My repo is here: https://github.com/AutoSponge/books. Based on what was happening before on MacOSX, node v8.7.0, if you change bankai to latest, it will start getting flaky.

**Comment by Flet** [comment]
Running `DEBUG=* npm run build` on the `books` repository, I can see `common-shakeify` blowing up when trying to process `utils.js`:
```js
exports.status = function (response) {
  if (response.status > 399) {
    throw new Error(`${response.status}: response from service.`)
  }
  return response
}

exports.json = response => response.json()
exports.handlError = error => console.error(error)
```

It looks like `acorn@5.1.2` does not like fat arrow functions on `exports` definitions?

If I change it to plain old functions then it succeeds:
```js
exports.status = function (response) {
  if (response.status > 399) {
    throw new Error(`${response.status}: response from service.`)
  }
  return response
}
exports.json = function (response) { response.json() }
exports.handlError = function (error) { console.error(error) }
```

Since `acorn@5.1.2` is the latest version, I an issue may need to be opened with them (I didn't see one when I quickly checked).

Sorry you ran into this! Updating `utils.js` in the `books` repo would be the quick fix :)

**Comment by goto-bus-stop** [comment]
yep, common-shakeify was generating incorrect output when using an arrow function in `exports.xyz = () => {}`. fixed in 0.4.3.

**Comment by Flet** [comment]
@goto-bus-stop nice!

**Comment by goto-bus-stop** [comment]
> When I didn't get this error, I got the message in the browser that I had no routes (there's only one /* route).

hmm, maybe the same issue as in #281?

**Comment by yoshuawuyts** [comment]
Is this still an issue?

**Comment by AutoSponge** [comment]
I think it can close. Thanks!

**Comment by yoshuawuyts** [comment]
Yay, happy it worked out alright! ☺️
