### ISSUE TITLE
Disable HTTPS?

### ISSUE THREAD

**Issue by simonwjackson** [choojs/bankai#307]
Is there any way to start bankai without HTTPS?

I need to access resources that are HTTP, and all browsers are blocking this

**Comment by yoshuawuyts** [comment]
Oh that's odd; there should be no reason why an HTTPS site can't access HTTP; this is new to me for sure. What errors are you seeing? Is there perhaps some header we can set that would enable this? Thanks!

**Comment by simonwjackson** [comment]
This is what i get when i load bankai:

![capture](https://user-images.githubusercontent.com/189379/32176256-2ae4784a-bd55-11e7-9ba2-f98682a80b8b.PNG)

I can choose to "proceed" but then i still cant access my HTTP resource

![capture2](https://user-images.githubusercontent.com/189379/32176257-2af62702-bd55-11e7-8555-bbb82e827c18.PNG)

**Comment by yoshuawuyts** [comment]
Ghmm, odd — that shouldn't be happening. The warning screen is expected, but the request failing is not. My gut feeling tells me it's CORS related, but we're already setting all required flags everywhere. I'm not quite sure what's going on.

**Comment by toddself** [comment]
Its been a few years since I've had to deal with this until i ran into the same issue on Friday.  It's very likely that you need to have your *system's* trust store trust the cert, not just telling the browser to ignore the warning.

**Comment by yoshuawuyts** [comment]
There's probably two things you can do here:
- roll your own bankai server using `require('bankai/http')`, and don't use https
- add https to your `8081` server by using the certs in `~/.config/bankai`

Rolling your own server shouldn't be too hard; it's basically just this https://github.com/choojs/bankai#http.

I'm a bit reluctant to introduce an option to disable https for the `start` command, as we're still actively iterating on the feature set, and adding flags
makes it harder to iterate with our limited resources. Hope it makes sense. Thanks!

**Comment by yoshuawuyts** [comment]
Hope the question here was answered; closing for now — let us know if there's anything else we can help with!
