### ISSUE TITLE
Error with electron

### ISSUE THREAD

**Issue by emilbayes** [choojs/bankai#308]
Bankai doesn't like this script very much:

```js
// index.js
var ipc = require('electron').ipcRenderer
```

```sh
bankai start index.js
```

Gives the following error:

```
Uncaught TypeError: fs.existsSync is not a function
    at Object.<anonymous> (index.js:6)
    at Object.3.fs (index.js:11)
    at s (_prelude.js:1)
    at _prelude.js:1
    at Object.1.electron (index.js:1)
    at s (_prelude.js:1)
    at e (_prelude.js:1)
    at _prelude.js:1
```

DevTools reporting `index.js` as:

```
var fs = require('fs')
var path = require('path')

var pathFile = path.join(__dirname, 'path.txt')

if (fs.existsSync(pathFile)) {
  module.exports = path.join(__dirname, fs.readFileSync(pathFile, 'utf-8'))
} else {
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
}
```

If I however do the require in `index.html` it all works fine, which is why I suspect it may be bankai that causes the error?

**Comment by yoshuawuyts** [comment]
Oh boy; yeah for now I'd recommend using bankai v8 still — and if you need access to Node APIs, try running `window.require()` instead of regular `require()`. I know @blahah has been working on this problem too; perhaps sharing notes might be useful.

Sorry I don't have a better answer for now; kinda spread thin haha.

**Comment by emilbayes** [comment]
That's okay :heart: Just wanted to leave a bug report in case someone else encounters the problem!

**Comment by yoshuawuyts** [comment]
yay, glad! Closing for now as it's not really actionable — if that's ok (: Thanks for raising!
