### ISSUE TITLE
Bankai sheetify transform

### ISSUE THREAD

**Issue by emilbayes** [choojs/bankai#311]
I tried using a transform with sheetify, but I think the documentation on how to configure them is wrong. The following gist does not load `sheetify-nested`, and checking the `options.use` property in sheetify reveals that it is indeed empty.

https://gist.github.com/emilbayes/5e7519883dd1212f69c60c5afb815fdc

I'm happy to help, but I'm not sure where this should be set. Merged with `.use` here? https://github.com/stackcss/sheetify/blob/2b5722aa7d77b8cb78644177d6308c848cc27991/index.js#L85

**Comment by emilbayes** [comment]
maybe it should be a goal to incorporate module-deps into sheetify so all this stuff is the same as browserify (I say this barely knowing anything about sheetify internals)

**Comment by Flet** [comment]
This sounds like a good idea

**Comment by yoshuawuyts** [comment]
@emilbayes we use [style-deps](https://github.com/stackcss/style-deps) to do the same thing as module-deps does, but being able to track `.css` files and the `.style` key in `package.json` — I'm not sure what's going wrong right now, but any fix would be much appreciated!

**Comment by yoshuawuyts** [comment]
@emilbayes ping; any updates on this? If not, can we close?

**Comment by timsim00** [comment]
Using nested css breaks [my app](https://github.com/timsim00/choo-baqend-starter) unless I modify the sheetify module like so:
function applyTransforms (filename, src, options, done) { **options.use = 'sheetify-nested'**

Here's what I think should work in package.json but doesn't:

  "sheetify": {
    "transform": [
      "sheetify-nested"
    ]
  },

**Comment by goto-bus-stop** [comment]
I think sheetify still uses the `use` terminology atm. there is a PR https://github.com/stackcss/sheetify/pull/135 to switch to `transform`.

does doing

```json
"sheetify": {
  "use": ["sheetify-nested"]
}
```

work as expected?

**Comment by timsim00** [comment]
Still breaks with "use".

**Comment by goto-bus-stop** [comment]
does this work now since sheetify@7.0.0 has been released?

**Comment by goto-bus-stop** [comment]
Think this is fixed in recent sheetify versions; please reopen if not. Thanks!

**Comment by timsim00** [comment]
Upgrading to 7.3.0 and adding
```
"sheetify": {
  "use": ["sheetify-nested"]
}
```
to package.json resolved the issue for me.  Thank you!
