### ISSUE TITLE
node v8.8 - HTTP2 issue? 

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#313]
Having some issues with upgrade to node 8.8

Bankai falls over when a website reloads ... I don't get much more in the logs other than an ELIFECYCLE error.

```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! descartes@1.0.0 dev: `bankai start index.js`
npm ERR! Exit status 1
```

**Comment by laduke** [comment]
Think you're on the right track 
`NODE_NO_HTTP2=1 npm start` seems to not crash

**Comment by shotlom** [comment]
Ref #238

**Comment by yoshuawuyts** [comment]
Dang, yeah tried it too today, and things aren't working the way it's supposed to be. On my end we're experiencing a double close error, which might be an artifact from the pre `v8.8.x` days. Going to dig into this a bit soon.

**Comment by yoshuawuyts** [comment]
I'm having trouble reproducing this consistently on master. Just published master as `v9.0.0-rc9` — could you check if that still causes issues? Worst case it should now have a clearer error message on failure. Thanks!

**Comment by shotlom** [comment]
Downloaded a new choo app with ```npx create-choo-app```. It has bankai@v9.0.0-rc9. Here is the result .. I like the new hot pink button!

![choo-fault](https://user-images.githubusercontent.com/398402/32231740-2873c6d0-bea2-11e7-9a17-f047eb034e6a.gif)

**Comment by shotlom** [comment]
[2017-10-31T15_11_06_201Z-debug.log](https://github.com/choojs/bankai/files/1431219/2017-10-31T15_11_06_201Z-debug.log)

**Comment by yoshuawuyts** [comment]
@shotlom could you perhaps just post a screenshot with the output? I'm having trouble with the log file; it seems it's mostly outputting verbose npm output, and I'm looking for the error bankai returned. If there wasn't any, that's fine too — but at the moment I don't quite know how to further assist haha. The gif cuts out before I can really look at the error (:

**Comment by shotlom** [comment]
![image](https://user-images.githubusercontent.com/398402/32250970-8e2cb800-beda-11e7-9b01-a347c0d8feab.png)

**Comment by shotlom** [comment]
Yeah, I'm also having trouble finding a good debugging output for you to help with the diagnosis. The screenshot above has logs written to multiple command lines which doesn't help ... not sure if that's a configuration problem at my end, or a feature of the bankai error.

**Comment by shotlom** [comment]
So the issue comes when reloading the browser window ... 
![image](https://user-images.githubusercontent.com/398402/32251150-82b214b0-bedb-11e7-87ae-cf91f6b8ffef.png)

**Comment by shotlom** [comment]
But it also seems to come when I save an adjustment to a file. By this I mean that when bankai attempts to reload the browser after I've made a change to a source file, bankai is lost.

**Comment by shotlom** [comment]
![choo-fault2](https://user-images.githubusercontent.com/398402/32251573-470e3a54-bedd-11e7-9449-f7659e11a10f.gif)

**Comment by shotlom** [comment]
btw ...  I also just tested in Node v9.

![image](https://user-images.githubusercontent.com/398402/32254905-c146d49a-beef-11e7-8888-2fe0b08fbd63.png)

**Comment by yoshuawuyts** [comment]
Argh; alright. Looks like this code is no longer working as intended https://github.com/choojs/bankai/blob/master/http.js#L194-L199

**Comment by yoshuawuyts** [comment]
Opened up an issue on Node core to figure this out how to fix this https://github.com/nodejs/node/issues/16666

**Comment by apapirovski** [comment]
@yoshuawuyts you could add a little extra safety check to `write` that only fires if `!res.finished`.
