### ISSUE TITLE
Configuring the polyfill.io transform / Transform execution order

### ISSUE THREAD

**Issue by espy** [choojs/bankai#315]
Hi there, thanks for Choo and all the amazing things that come with it! 

I’d like to have Bankai/Documentify insert the polyfill.io script tag with a few feature options, since I need to support IE11 and the `Array.prototype.find` polyfill isn’t loaded automatically:

```html
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Array.prototype.find" defer></script>
```
Since I can’t configure that original transform, my idea was to [add a new transform to Documentify](https://github.com/choojs/bankai#configuration), but my custom transform runs _before_ the transforms in `graph-document.js` that adds the polyfill script (since [12 days ago](https://github.com/stackhtml/documentify/pull/12) 😅 ) , so that can’t ever work. 

Sooo yeah. I’d be super grateful for any pointers on how to best achieve this. If this turns out to be really difficult, I could always use Babel’s polyfilling, but if there's a way to do this nicely in the build step I’d be happy to know :)

Thanks a lot in advance!

**Comment by yoshuawuyts** [comment]
@espy I'm thinking we might drop polyfill.io entirely in the near future, and instead opt for using babel. Polyfill doesn't play well with Integrity checks (e.g. script shasums), certain corporates are wary of running 3rd party code, and during development the experience isn't great.

I think in the short term manually plugging in babel might make more sense; and if anything is missing from `documentify` opening up an issue there might be the right way to go too!

Does this allow you to proceed? I'm totally open to adding more flags to `polyfill.io` too if that's easier. Thanks for raising this! :sparkles:

**Comment by espy** [comment]
Thanks for the speedy reply! @goto-bus-stop is already on it with a good proposal, I see. And dropping polyfill.io… why not, anyone who needs it can add it in fairly easily.

I’m actually currently struggling to get browserify + babelify to work properly in bankai, might open an issue for that tomorrow if I don’t get anywhere.
