### ISSUE TITLE
Can’t get Babelify transform to work (aim is IE11 support)

### ISSUE THREAD

**Issue by espy** [choojs/bankai#319]
Hiya,

right off the bat: I’ve got a sneaky feeling that I’m totally on the wrong path to solve the fundamental problem I’m having: making sure my choo app runs in IE11. If there’s a better way to do this, I’m not married to Babel(ify) at all. 

I’m struggling to get a Bankai (`^9.0.0-rc7`) -> Browserify -> Babelify(`^8.0.0`) thing going. I was assuming it’s just 

```
npm i babel-preset-env babelify babel-core
```

(let’s leave out the 7.0.0 betas for now)

and then adding this to the `package.json`:

```javascript
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "presets": [
            [
              "env",
              {
                "targets": {
                  "browsers": [
                    "last 2 versions",
                    "safari >= 7",
                    "ie >= 11"
                  ]
                }
              }
            ]
          ]
        }
      ]
    ]
  },

```
This gets picked up and actually does something, for example arrow functions get converted, but the code as a whole breaks: there are undefined functions because some `require`s apparently don’t get resolved properly. For example:

```javascript
D={},R=function(e){return D(C,e)}
```
`D` in this case is the minified version of the `html` variable in `const html = require('choo/html')`, but as you can see it’s empty.

Not sure where to go from here. Am I missing something obvious somewhere? Or has anyone got a working example lying around? I’ve seen that some of the showcase apps in `awesome-choo` circumvent this by not using Bankai at all, but it would be so cool if it worked directly :D

Many thanks <3

**Comment by goto-bus-stop** [comment]
I think babel is transforming template strings first, and then the yo-yoify browserify transform does not see any template strings it can use. You could try adding https://www.npmjs.com/package/babel-plugin-yo-yoify, that way template strings can be transformed during the babel step, before the yo-yoify browserify transform.

**Comment by espy** [comment]
Hah, brilliant, thanks! That got me one step further. Now I just have to get all the polyfills in properly. For future reference, this works:

```javascript
  "browserify": {
    "transform": [
      [
        "babelify",
        {
          "plugins": [
            "yo-yoify"
          ],
          "presets": [
            [
              "env",
              {
                "targets": {
                  "browsers": [
                    "last 2 versions",
                    "safari >= 7",
                    "ie >= 11"
                  ]
                }
              }
            ]
          ]
        }
      ]
    ]
  },
```

**Comment by YerkoPalma** [comment]
haha if there is a callback hell, this would be json hell?

**Comment by espy** [comment]
Wuuuh. Got everything working. Nice nice. Thanks again!
