### ISSUE TITLE
Babelify config for Browserify does not work with rc10

### ISSUE THREAD

**Issue by kahlil** [choojs/bankai#329]
I use the following Browserify config:

```js
"browserify": {
	"transform": [
		[
			"babelify",
			{
				"presets": [
					"env"
				]
			}
		]
	]
}
```
And Bankai can't parse the `import` syntax:

```
Failed while processing 'scripts'.

 --> index.js:2:1
  |
2 | import { html, render } from 'lit-html';
  | ^ Syntax Error

Hmmm. We're having trouble parsing a file.
```
The necessary modules are installed.

**Comment by yoshuawuyts** [comment]
Oh, that's odd. I would've expected https://github.com/shama/yo-yoify/pull/58 by @goto-bus-stop to have solved our final compat issues. My guess is there's probably some parser in the tree that's operating on an outdated version.

Also, on a side note we're going to be baking in Babel support for stable language features sometime in the next 2 weeks. Hopefully that'll fix this issue in the long run C:

**Comment by kahlil** [comment]
👍  for baking Babel in! Still this simple Browserify config should still work, right?

**Comment by yoshuawuyts** [comment]
Yeah, I would've expected it to! Not sure why it isn't parsing the `import` syntax. [Here's a project where we're using browserify transforms too](https://github.com/yoshuawuyts/millennial-js/blob/master/package.json#L11-L15). So I don't think it's being glossed over, ghmmm. I'm still suspecting a transform using an outdated parser somewhere.

Could you perhaps run `bankai build` to see if it crashes with a different error? Thanks!

**Comment by kahlil** [comment]
This is the output on `bankai build`: 

```
❯ npx bankai build
14:30:28 ✨  Compiling & compressing files

14:30:28 ✨  created: dist
14:30:28 🚨  bankai.asset: could not find a file for 
14:30:28 ✨  created: dist/manifest.json
14:30:28 ✨  created: dist/manifest.json.gz
14:30:28 ✨  created: dist/manifest.json.deflate
14:30:28 ✨  created: dist/manifest.json.br
14:30:28 🚨  Failed while processing 'scripts'.

 --> index.js:2:1
  |
2 | import { html, render } from 'lit-html';
  | ^ Syntax Error

Hmmm. We're having trouble parsing a file.
```

**Comment by yoshuawuyts** [comment]
Ugh; looks like we did _too good_ of a job on prettifying errors >.>

Let me try and repro this. Be back with you in a bit!

**Comment by kahlil** [comment]
thanks!

**Comment by yoshuawuyts** [comment]
Okay, looks like `brfs` is the culprit here. For a quick fix, apply the following patch to bankai:
```diff
diff --git a/lib/graph-script.js b/lib/graph-script.js
index 86d345a..2e4d083 100644
--- a/lib/graph-script.js
+++ b/lib/graph-script.js
@@ -37,7 +37,7 @@ function node (state, createEdge) {
 
   b.ignore('sheetify/insert')
   b.transform(sheetify)
-  b.transform(brfs)
+  // b.transform(brfs)
   b.transform(glslify)
   b.transform(yoyoify, { global: true })
 
@@ -51,6 +51,7 @@ function node (state, createEdge) {
     self.emit('progress', 'scripts', 30)
 
     b.bundle(function (err, bundle) {
+      console.log('error', err)
       if (err) {
         delete err.stream
         err = ttyError('scripts', 'browserify.bundle', err)
```

Recommended to run without switching buffers through the `-q` flag.
```sh
$ bankai start -q
```

It seems after this patch is applied there's still some errors related to importing source type module style modules from within Node. So there may be a few more hurdles, ugh. Let me dig a little further on how to solve this, ghmmm.

**Comment by kahlil** [comment]
Thanks Yosh.

**Comment by yoshuawuyts** [comment]
Oh, no yeah think I figured it out — I think the transform needs to be _global_ because `lit-html` uses the `export` keyword, and locally defined transforms don't operate globally. Alright, let's get Babel support into core! @kahlil any presets you generally use?

**Comment by goto-bus-stop** [comment]
Passing `"global": true` to the babelify transform options should also make it run globally, im 80% sure


On 14 November 2017 14:58:06 CET, Yoshua Wuyts <notifications@github.com> wrote:
>Oh, no yeah think I figured it out — I think the transform needs to be
>_global_ because `lit-html` uses the `export` keyword, and locally
>defined transforms don't operate globally. Alright, let's get Babel
>support into core! @kahlil any presets you generally use?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/choojs/bankai/issues/329#issuecomment-344266769

-- 
Sent from mobile. Please excuse my brevity.

**Comment by kahlil** [comment]
oh yeah yeah that's not an issue I just added the same config into the lit-html package.json to make that work. A global transform is not advisable I think. 

My problem was just that the transform did not apply to _my file_.

When it comes to presets I am just interested in the default `env` presets. 
I think what would be interesting as well would be rollup support :)

**Comment by yoshuawuyts** [comment]
Waiting for `brfs` & `static-module` to be moved to the Browserify org. Related patches:
- [ ] https://github.com/substack/static-module/pull/29
- [ ] https://github.com/substack/static-module/pull/35
- [ ] patch to bump `brfs` to use the new parser

---

> I think what would be interesting as well would be rollup support :)

@kahlil Oh cool! — what would you like to see from Rollup? We have tree shaking, bundle flattening, and soon code splitting too (in https://github.com/choojs/bankai/pull/266). Would we be missing anything? (:

**Comment by kahlil** [comment]
> We have tree shaking, bundle flattening, and soon code splitting too (in #266). Would we be missing anything? (:

Oh, well don't mind me then, that sounds perfect 😄 .

**Comment by yoshuawuyts** [comment]
Added a PR to add Babelify into Bankai directly here https://github.com/choojs/bankai/pull/332 :tada: — If this doesn't land straight away, we should at least be publishing the `brfs` patch within the next 24 hours. Thanks!

**Comment by kahlil** [comment]
✨

**Comment by yoshuawuyts** [comment]
`bankai@9.0.0-rc11` has been published; no babel yet, but it should work with the transforms in `package.json` at least.

We're probably going to release `rc12` with Babel support & code splitting in the next few days, with bankai 9 stable (hopefully) before the end of the week :tada:

**Comment by kahlil** [comment]
Works-a like-a deh charm-a! (Mario voice)

🙏  thanks y'allz are super.

**Comment by yoshuawuyts** [comment]
Yay, glad to hear!
