### ISSUE TITLE
Make output directory configurable

### ISSUE THREAD

**Issue by rreusser** [choojs/bankai#333]
Trying out bankai and loving it so far! I make sorta heavy use of github pages, so it'd be convenient if I could output to `docs/` instead of `dist` without having to `mv` the result into place. I definitely respect the lack of command line configuration, but I'm curious whether there might be a place for this or if there's a good alternative. (P.S. No is a perfectly good answer 😄)

**Comment by yoshuawuyts** [comment]
I was thinking it might be convenient to do this:
```sh
$ bankai build && mv dist docs
```

**Comment by yoshuawuyts** [comment]
Oh, perhaps we could do:
```sh
$ bankai build index.js docs/
```
No extra flags, but pretty straight forward C:

**Comment by rreusser** [comment]
Ahh, I think I misunderstood the service worker + hashed contents stuff. I wasn't 100% certain whether you build into the same directory and it updates the hashes etc (which I guess would be a bit stateful 😬) or whether you just rm -rf and rebuild. If I understand correctly, suddenly `bankai build && mv dist docs` doesn't seem so bad.

**Comment by yoshuawuyts** [comment]
@rreusser oh, actually! — we might be doing an optimization step for assets later on (e.g. don't copy if they already exist), so having an explicit out directory might be useful for that. PR welcome!

**Comment by goto-bus-stop** [comment]
https://github.com/choojs/bankai/pull/416

**Comment by rreusser** [comment]
(Sorry I never got to this 😞. Found a new job sooner than expected so that open sourcery kinda fell by the wayside. The above PR looks great though!)
