### ISSUE TITLE
React support

### ISSUE THREAD

**Issue by isaachinman** [choojs/bankai#339]
From `yoshuawuyts`'s Reddit account:

    Heya, Bankai maintainer here. We've mostly been focused on making it work with Choo out of the box, because that's what we use — but adding support for React should be straight forward.
    Probably all that's needed is:
      1. a Babel plugin to compile .jsx files in lib/graph-scripts.js
      2. a way to server-render React apps inside lib/server-render.js
    Pull requests would be very welcome!

I'd be interested in putting together a PR for this if the maintainers can provide a bit more info as to how they would expect React support to look (separate branch? master? CLI option?).

**Comment by yoshuawuyts** [comment]
> I'd be interested in putting together a PR for this if the maintainers can provide a bit more info as to how they would expect React support to look (separate branch? master? CLI option?).

Sweet; that'd be amazing!

I think we could probably add React support with very little overhead:

### JSX support
In [lib/graph-scripts](https://github.com/choojs/bankai/blob/master/lib/graph-script.js#L55-L62), we would need to add the Babel JSX plugin to compile `.jsx` files. If there's a `jsx` transform for Browserify, that'd be welcome too; although I suspect Babel might perhaps be the more common option.

### Server Rendering
In [lib/server-render](https://github.com/choojs/bankai/blob/master/lib/server-render.js), we would need to add an extra fingerprint to detect what type of framework we're dealing with, and then stringify it correspondingly. React should return the following values:
```js
{
      body: body || '<body></body>',
      title: title || '',
      language: language || 'en-US'
}
```
The code in `server-render` is a little bit messier than we'd like, but hopefully once we land a patch, we could work on a refactor.

### Tests
Probably an extra test for server-rendered react might be useful. We should have some for documents in our `tests/` directory. That way we can catch regressions, and stay committed to supporting React going forward Modeling it similarly to existing tests would be great.

---

I think once we have SSR, and can read `JSX` files, there shouldn't be much more left. Perhaps respecting async rendering would be fun, but it seems approaches vary. Perhaps we should leave that for a follow up patch?

Hope this is enough to get started with!

**Comment by morenoh149** [comment]
What exactly do you mean by react support?
A recipe for adding react to a bankai project or something in the wizard.

**Comment by yoshuawuyts** [comment]
@morenoh149 e.g. instead of using `choo`, you can use `React` with SSR, styles, the works (:
