### ISSUE TITLE
Consider support for custom index.html files?

### ISSUE THREAD

**Issue by johanalkstal** [choojs/bankai#343]
As I understand it, bankai brings its own index.html file.

I see issues with not being able to supply your own file or template for an index.html file.
Some of the default attributes potentially block people from using bankai due to other cultural needs, like `lang` being set to american english by default, or `dir` being set to `ltr` by default.

Then of course there's the very likely need to have custom meta tags in the head of the document.

I've come to understand that there's a "hack-ish(?)" way to add things like that through `documentify`?

But I feel things like these should be as simple as possible to do without any special knowledge.

What are your thoughts?

**Comment by dolebas** [comment]
In regards of custom head, what is your opinion on setting the head dynamically and redirect bots to a pre-rendering service?

**Comment by johanalkstal** [comment]
@dolebas From the top of my head that sounds more complicated than things should be? But I've never had the need or attempted something similar.

**Comment by dolebas** [comment]
In my experience, this approach can actually make it easier to customise the head. If you are using Netlify, they support this out of the box but other solutions like redirecting with Firebase Functions is quite straight forward as well.

**Comment by johanalkstal** [comment]
In regards to the head, relying on a third party to provide you with a service doesn't sound like a reasonable default.

But dynamics is not the issue I'm talking about. It's about being in control of your document. 

The most simple solution for the user of bankai has to be to provide bankai with a index.html template. The developer has to have control over how their document looks and is structured.

**Comment by dolebas** [comment]
In case you are not hosting your site on your own servers, there's actually no need to rely on an additional third party for this approach.

As your document lives in the DOM client side, your control over the document should increase when you define it with JS. Server side, as all the bots don't execute JS, a headless browser setup can provide a simple and generic solution.

I like that bankai simply takes care of the html per default but having the ability to optionally provide html templates sounds great.

**Comment by goto-bus-stop** [comment]
the assumptions bankai makes about the document during SSR are also going to be a problem for adding React/Preact support. in bankai, the app is expected to handle the entire `<body>` element, but in (p)react apps you'd usually mount the app into an element like `<div id="app">`. that'd also be a useful case for custom templates.

def think we should do this!

**Comment by YerkoPalma** [comment]
Definitly +1 on this because 1) Was prebiously supported by bankai, and users (like me) would expect this to keep working. 2) In choo, you also could mount your app in some other node different than body

**Comment by alexbihary** [comment]
Also +1 on this feature. I'm starting to use choo for a project, but I want more control of the html templates. I need to actually create several different templates to mimic different scenarios that the js project will need to work with (different clients will load the js in different places/ways).

**Comment by yoshuawuyts** [comment]
Ah dang, yeah perhaps we should pick this up then. [documentify](https://github.com/stackhtml/documentify/) still supports, this but we would need to turn it on.

Think all we need to do is change a few lines in [lib/graph-document.js](https://github.com/choojs/bankai/blob/master/lib/graph-document.js#L69). @alexbihary would you want to make a PR? :D
