### ISSUE TITLE
Stylesheet not loading in latest Safari

### ISSUE THREAD

**Issue by jondashkyle** [choojs/bankai#346]
It looks like setting the `rel="stylesheet"` attribute onload does not work in the most recent Safari. Changing this to simply declare `rel` by default correctly loads the stylesheet, but am unsure if preloading works as intended.

```
<link rel="preload" as="style" href="/6b2bede60756eb41/bundle.css" rel="stylesheet">
```

https://developer.mozilla.org/en-US/docs/Web/HTML/Preloading_content#The_basics

**Comment by yoshuawuyts** [comment]
Yeah, i think we are trying to redeclared this.rel. perhaps we need to clear it first?

**Comment by jongacnik** [comment]
perhaps useful, this is an example of the type of async css we're trying to achieve. It runs in most recent Safari, but that is because there is a polyfill in the source

https://master-origin-loadcss.fgview.com/test/preload.html

**Comment by greggraf** [comment]
@yoshuawuyts - it looks like the polypill is already in there. It just appears that the script block is not getting processed, and I think its the `nomodule` and `integrity` attributes on the generated `script` tag.

when I remove them from https://github.com/choojs/bankai/blob/master/lib/graph-document.js#L111 locally, the polypill works for me and my css loads in mobile safari.

I don't think those attributes belong on an inline script tag. I will put together a pull request.

**Comment by gavinpatkinson** [comment]
this still appears to be an issue

**Comment by yoshuawuyts** [comment]
@greggraf this issue should now be fixed, right? :D

**Comment by greggraf** [comment]
@yoshuawuyts - when I check with Bankai v9.2.1 on desktop Safari I see the css getting requested in the network tab and rendered on my page.

**Comment by goto-bus-stop** [comment]
:100: thanks!
