### ISSUE TITLE
Adding more examples

### ISSUE THREAD

**Issue by bjrnt** [choojs/bankai#347]
Hello!

I’ve recently been playing around with `create-choo-app` and having lots of fun in the process. I thought it might be good to add additional examples to bankai for new people, e.g. for things like “how can I use TypeScript/SVGs/some-library together with Bankai?” One example of an open-source library that does this kind of thing particularly well is [Next.js](https://github.com/zeit/next.js/tree/canary/examples).

One example setup that I’d personally be happy to contribute with is showing how you can load markdown files without breaking SSR (my first attempt using Browserify failed at this). 

I’d be happy to create a minimal repo showcasing my approach and adding a link to it in awesome-choo, or I could add an example to this repo Next.js-style. Would love some feedback on how you’d like to handle these kinds of example setups! :)

**Comment by yoshuawuyts** [comment]
Heya, glad you're having a good time!

What we noticed is that having examples in the repo can become a bit tricky to maintain. So what I think might work best is if you create a standalone example, and then at some point we write docs around this. Would that work for you? Thanks!

**Comment by bjrnt** [comment]
Absolutely!

Here's an example repo I've put together:
https://github.com/bjrnt/bankai-with-markdown

I hope this will be of help to others who want to create blogs or other content-centric sites using bankai. :)
