### ISSUE TITLE
WASM Brotli

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#358]
We should investigate using this - https://github.com/dfrankland/wasm-brotli. Having to compile at the moment is slow, and a lil annoying haha.

**Comment by yoshuawuyts** [comment]
Tried running this with a static server, but it seems it doesn't work as expected. Probably an issue with `wasm-brotli` 😢 

```js
var http = require('http')
var path = require('path')
var fs = require('fs')

http.createServer(function (req, res) {
  res.writeHead(200, {
    'Content-Type': 'text/html',
    'Content-Encoding': 'br'
  })

  fs.createReadStream(path.join(__dirname, 'index.html.br'))
    .pipe(res)
}).listen(8085, function () {
  console.log('listening on 8080')
})
```

**Comment by dfrankland** [comment]
Yep, there definitely seems to be some issue with `compress`.

Just adding changing 1 character in a string can break it apparently. Take a look at the example below:

```js
const { compress, decompress } = require('wasm-brotli');

const badHtml = `
  <!doctype html>
  <html>
    <head>
      <title>Testing!</title>
    </head>
    <body>
      <h1>Hello, world!</h1>
    </body>
  </html>
`;

const goodHtml = `
  <!doctype html>
  <html>
    <head>
      <title>Testng!</title>
    </head>
    <body>
      <h1>Hello, world!</h1>
    </body>
  </html>
`;

(async () => {
  await Promise.all([goodHtml, badHtml].map(async (content) => {
    try {
      const buffer = Buffer.from(content, 'utf8');
      const compressed = await compress(buffer);
      const decompressed = await decompress(compressed);
      const newContent = Buffer.from(decompressed).toString('utf8');
      console.log(`This one works!\n${newContent}`);
    } catch (err) {
      console.error(`This one failed!\n${content}`);
    }
  }));
})();
```

The only character that is changed is the `i` in `Testing!`.

**Comment by goto-bus-stop** [comment]
thanks for digging into this @dfrankland! for reference, looks like this was the core issue: https://github.com/dropbox/rust-brotli/issues/15

**Comment by danielrh** [comment]
I fixed the bug in brotli: can you update the crate to 1.1.1 and try again?

**Comment by dfrankland** [comment]
I've ran a couple of tests with `wasm-brotli@1.0.2` and everything seems to work now that it includes the `brotli@1.1.1` crate (thank you @danielrh).

**Comment by yoshuawuyts** [comment]
I tried running this on my example above, and it all seems to be working! :tada:

**Comment by goto-bus-stop** [comment]
b3d71541dbca3df05926b333eac0c85cabd701d8, thanks again! :D
