### ISSUE TITLE
Use nanobus?

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/bankai#364]
Is there a reason to use Node EventEmitter instead of Nanobus? since they have the same API AFAIK, and Nanobus is smaller?

**Comment by yoshuawuyts** [comment]
@YerkoPalma haha, well because Bankai runs natively in Node, the Node event emitter is technically smaller. Because it's part of the runtime. Because we're using streams in places, it'll always need to be loaded, so not using Nanobus means we can skip another dependency.

Does that make sense?

**Comment by YerkoPalma** [comment]
Oh I see, makes sense to me :)
