### ISSUE TITLE
Regex router ignoring some valid paths

### ISSUE THREAD

**Issue by YerkoPalma** [choojs/bankai#367]
In `bankai/http`, the regex-router ignore some valid paths like

```txt
/index.dev.js
```

The above route should be cauhgt by the js regex, but this regex only expect 1 dot, the one before the js extension.

```js
/\/([a-zA-Z0-9-_]+)\.js$/
```

So that route is handle by the default route which set a `text/html` content-type header (which will throw in some cases). This problem is extensible for css ~and source map~ files, but I don't think those will throw (still feels wrong to serve a css file like an html file)
**edit:** This doen's affect source maps, in fact source map consider the extra dots, this should be applied to js and css files too.

A second wrong route parsing is with queryStrings like

```txt
/assets/my-file.txt?version=1.0
```

The assets route will catch that, but will look for a file named `my-file.txt?version=1.0` which doesn't exists, so it will throw a 404 error. this is because the regex

```js
/^\/assets\/(.*)$/
```

just catch anything after `/assets/`, including the querystring. Not sure of the impact of this, but I guess some external services, like cdn use querystrings on files (it happened to me with workbox service).

I hope now this is clear enough to solve the issue.

**Comment by yoshuawuyts** [comment]
@YerkoPalma hey, thanks for tracking this down! - if you have time, do you want to write a patch for it?
