### ISSUE TITLE
Server Side Rendering Skipped 

### ISSUE THREAD

**Issue by shotlom** [choojs/bankai#368]
Ok - so, I'm on bankai v9.1, node v.9.3.

I have an App use case where I want to show and populate the next page based on a user's selection.

## Step 1 - Select a Choo from a list of Choos: 

![image](https://user-images.githubusercontent.com/398402/34634882-aa240456-f2dc-11e7-95ae-2d2d1a93598e.png)

## Step 2 - Navigate to the Choo Details page that has all the details of the selected Choo. Like so:

![image](https://user-images.githubusercontent.com/398402/34634888-be6c35c8-f2dc-11e7-8cef-c53b67964d32.png)

## So what is the problem? 

Because the Choo details page needs to have it's contents populated dynamically, Bankai says:

>Bankai: "whoooa there! You do realise that is a dynamic population of state.chooDetails.title don't you?"
>Me: "Yeah so, so what?"
>Bankai: "Well that means, and I quote, 'Cannot read property 'title' of undefined at view', so I'm going to, 'Server Side Rendering: Skipped' you"
>Me: "Oh!"
>Me: "So hold on, how to I create an app that has Server Side Rendering and uses the choo-state dynamically?"
>FIN

**Comment by shotlom** [comment]
# So the question

How do I combine Server Side Rendering with pages whose content is dynamically populated based on user input?

**Comment by shotlom** [comment]
To add to this;

... this becomes a problem for bankai because it won't render the page reliably. 

I'm unable to access the page during development when Bankai says Server Side Rendering Skipped

**Comment by nicknikolov** [comment]
Dunno if I understand your problem correctly but would it help if you take the param from the url rather than `state`? E.g. each todo item has a unique URL based on its ID or something.

**Comment by shotlom** [comment]
@nicknikolov thanks for the response 

I might have not used available features.

here is my code for the todo page. Bankai is complaining about **${todo.title}**

```javaScript
'use strict';

const html = require('choo/html');
const css = require('sheetify');
const appBar = require('./appBar.js')

module.exports = view

function view (state, emit, render) {
  let currentTodo = state.params.currentTodo || 1;
  let todo = state['todos'][currentTodo];
  return html`
    <body class="sans-serif roboto">
      ${appBar(state, emit, render)}
      <div class="flex flex-column ph3 pt6">
        <div class="ttu f5 dim br-pill ph3 pv2 mb2 dib">
          ${todo.title}
        </div>
        <div class="f5 dim br-pill ph3 pv2 mb2 dib">
          Start:
        </div>
        <div class="f5 dim br-pill ph3 pv2 mb2 dib">
          Due:
        </div>
      </div>
    </body>`
}


```

**Comment by nicknikolov** [comment]
By complain you mean todo title is undefined? You can try doing something like `${todo ? todo.title : ''}` I think the other way way would be to add initial state to window as described here https://github.com/choojs/choo#server-rendering

**Comment by shotlom** [comment]
Yes, that's right. Sorry for my unclear reporting.

```
Server Side Rendering: Skipped - Cannot read property 'title' of undefined at view (/choo-concepts/views/todo.js:17:18)
```

**Comment by shotlom** [comment]
OMG!!! Whooohooo! @nicknikolov ```${todo ? todo.title : ''}``` totally worked!!! Thank you.
