### ISSUE TITLE
Inlined <style> CSS overwriting bundle.css

### ISSUE THREAD

**Issue by jondashkyle** [choojs/bankai#374]
I have some CSS which looks like this:

```
.bgr { background: red }
.bgb { background: blue }
```

1. I have two routes, `/` and `/example`
2. `/` has the class `.bgb`
3. `/example` has the class `.bgr`
4. If I navigate to `/`, then click a link and head to `/example`, the background is blue as `.bgb` in `bundle.css` is overwritten by the inlined CSS of `/`, which places `.bgr` above `bundle.css`.

My temporary fix is to simply remove the inlined CSS `<style>` when the DOM content has loaded. Perhaps this could be resolved by simply loading the `bundle.css` after the inlined `<style>` tag?

I can create an example somewhere if this is unclear! Cascading, yo!

**Comment by goto-bus-stop** [comment]
> Perhaps this could be resolved by simply loading the bundle.css after the inlined <style> tag?

this sounds like a good solution!
