### ISSUE TITLE
bankai report error when working with sass use sheetify-sass 

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/bankai#383]
step:
1. use [create-choo-app](https://github.com/choojs/create-choo-app) to create a choo app
2. use [sheetify-sass](https://github.com/stackcss/sheetify-sass) from package.json:
    ```json
      "browserify": {
        "transform": [
          [
            "sheetify",
            {
              "transform": [
                "sheetify-sass"
              ]
            }
          ]
        ]
      }
    ```
3. create a css file with sass syntax:
    ```css
    /* main.scss */
    div{
     p{
       color: black
     }
    }
    ``` 
4. load it with sheetify:
    ```js
    /* index.js */
    // ...
      var css = require('sheetify')
      css('./main.scss')
    // ...
    ```
5. run `bankai start index.js`

6. throw error:
    ```
    TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, 
    ArrayBuffer, Array, or Array-like Object. Received type undefined
    at Function.from (buffer.js:199:11)
    at BufferGraph.node (/Users/zhouhancheng/编程/chooapp/node_modules/bankai/lib/graph-style.js:31:31)
    at /Users/zhouhancheng/编程/chooapp/node_modules/buffer-graph/index.js:101:17
    at Array.forEach (<anonymous>)
    at /Users/zhouhancheng/编程/chooapp/node_modules/buffer-graph/index.js:96:22
    at /Users/zhouhancheng/编程/chooapp/node_modules/bankai/lib/graph-script.js:116:9
    at /Users/zhouhancheng/编程/chooapp/node_modules/bankai/lib/exorcise.js:59:5
    at /Users/zhouhancheng/编程/chooapp/node_modules/bankai/lib/exorcise.js:25:5
    at ConcatStream.<anonymous> (/Users/zhouhancheng/编程/chooapp/node_modules/concat-stream/index.js:36:43)
    at ConcatStream.emit (events.js:164:20)
    ```
7. change the `main.scss`'s syntax to basic css:
    ```css
    /* main.scss */
    div p{
       color: black
    }
    ``` 
   or, use `budo index.js --live`

8. then work out.

**Comment by yoshuawuyts** [comment]
Oh bizarre! Yeah, that shouldn't be happening.

**Comment by yoshuawuyts** [comment]
Ah, I've done some instrumentation to figure out what's going on - and think I've found two causes for this error.

## Package.json syntax
The syntax for the package.json should be:
```json
{
  "sheetify": {
    "transform": [
      "sheetify-sass"
    ]
  }
}
```
[example](https://github.com/yoshuawuyts/repro-bankai-383/blob/master/package.json)

## Upgrade Bankai
We're still using the (outdated) sheetify v6. We should upgrade to v7 as soon as possible. Created a PR for this in: https://github.com/choojs/bankai/pull/385.

## Bonus: sheetify-sass is out of date
We should really update `sheetify-sass`. It hasn't received updates in a while now, and dependencies are probably out of date. A PR to upgrade these would be amazing!

## Wrapping up
Hope this was helpful! I debugged these errors in https://github.com/yoshuawuyts/repro-bankai-383. You can `git clone` it to try it for yourself (although you'll need to go into `node_modules` and upgrade `sheetify` yourself, until the patch lands.)

Hope this resolves all your issues! :grin:

**Comment by ZhouHansen** [comment]
it works, thanks!

**Comment by ZhouHansen** [comment]
[PR](https://github.com/stackcss/sheetify-sass/pull/45) sended!

**Comment by yoshuawuyts** [comment]
Published! :grin:
