### ISSUE TITLE
watcher not work when modify css

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/bankai#386]
Still Using [repro-bankai-383](https://github.com/yoshuawuyts/repro-bankai-383)

run `bankai start index.js`

then modify css, bankai does not load the latest css even if refresh the browser manually.

**Comment by yoshuawuyts** [comment]
Oh dang, it probably means that sheetify isn't emitting files for `watchify`. A workaround for now would be to inline the files instead.

Could you perhaps open an issue on sheetify? Thanks!

**Comment by ZhouHansen** [comment]
[sheetify#144](https://github.com/stackcss/sheetify/issues/144), A friend open the issue on sheetify!

**Comment by yoshuawuyts** [comment]
Just got off a plane - @ZhouHansen fix in https://github.com/stackcss/sheetify/pull/145, a review / quick test if it works would be helpful! :D

**Comment by goto-bus-stop** [comment]
this should be fixed as of sheetify 7.2.0 and sheetify-sass 2.1.0!
