### ISSUE TITLE
add current package.json version to service worker

### ISSUE THREAD

**Issue by yoshuawuyts** [choojs/bankai#391]
As per https://github.com/choojs/create-choo-app/issues/43, it turns out we're not exposing the current `package.json` version in the service worker. It'd be cool if we did.

Was thinking we could go along with prior art and use [`process.env.npm_package_version`](https://stackoverflow.com/questions/9153571/is-there-a-way-to-get-version-from-package-json-in-nodejs-code) for that.

Thoughts? :grin:

**Comment by goto-bus-stop** [comment]
I think you can already do `require('../package.json').version`. common-shake should remove all the unused properties so it shouldn't leak any information. (brb checking)

**Comment by goto-bus-stop** [comment]
Yeah it does, and uglify even inlines the version number later!

```
$ cat sw.js
/* global self */
var VERSION = require('./package.json').version
...
$ npm run build
$ prettier dist/sw.js
...
    self.addEventListener("install", function(n) {
      n.waitUntil(
        self.caches.open("1.0.0").then(function(n) {
          return n.addAll(e);
        })
      );
    }),
...
```

**Comment by YerkoPalma** [comment]
Then this change belongs to `create-choo-app` repo right?

**Comment by goto-bus-stop** [comment]
I think this use case is addressed in https://github.com/choojs/create-choo-app/pull/44; please reopen if it's still relevant regardless
