### ISSUE TITLE
Bankai 9.3.1 not reload when css changes

### ISSUE THREAD

**Issue by paulogr** [choojs/bankai#393]
I've just update to 9.3.1 version and note that dev server doesn't reload when css file changes.
No errors were displayed.

Thanks

**Comment by stephenkistner** [comment]
Experiencing the same issue. Using sheetify-sass.

**Comment by yoshuawuyts** [comment]
released sheetify `v7.1.0` today! Reinstall your `node_modules` to get the fix in :sparkles:

If you're using `sheetify-sass` then https://github.com/stackcss/sheetify/issues/144 is probably still relevant. Hope this fixes your issues! :grin:

**Comment by goto-bus-stop** [comment]
sheetify 7.2.0 and sheetify-sass 2.1.0 also fixed the remaining issue with `@import`ed scss files. this should be all good now!
