### ISSUE TITLE
Bankai has support for code splitting?

### ISSUE THREAD

**Issue by paulogr** [choojs/bankai#409]
How do you guys handle it?
Thanks!

**Comment by goto-bus-stop** [comment]
with https://github.com/goto-bus-stop/split-require!

```js
var splitRequire = require('split-require')

splitRequire('./someModule', function (err, exports) {
  // called async w/ the exports of `./someModule.js`.
})
```

**Comment by paulogr** [comment]
Hi, sounds good.

Can I do route based lazy load? 
I mean when a user access some route the app dynamically load the bundle.

like this?

```
app.route('/lazyroute', (state, emit) => {
  splitRequire('./lazyview', (err, exports) {
    exports.lazyView(state, emit)
  })
})
```

**Comment by goto-bus-stop** [comment]
You can, but you have to do some work for it. I've been meaning to publish a choo-lazy-route module that makes it easier but didn't get to it yet.

Basically what you need to do is render a loading page while the bundle is loading, and then emit a 'render' event once the bundle has loaded. Something like this:

```js
app.route('/lazyroute', (state, emit) => {
  if (state.lazyView) return state.lazyView(state, emit)
  if (!state.loading) {
    splitRequire('./lazyview', onload)
    state.loading = true
  }
  return html`<p>loading</p>`
  function onload (err, exports) {
    if (err) state.error = err // can use this to render an error page
    else {
      state.lazyView = exports.lazyView
      emit('render')
    }
  }
})
```

**Comment by goto-bus-stop** [comment]
a work in progress choo-lazy-route module is now available at: https://www.npmjs.com/package/choo-lazy-route
