### ISSUE TITLE
It's not live-reloading

### ISSUE THREAD

**Issue by laduke** [choojs/bankai#420]
😬

- `npx create-choo-app foo`
- `npm start`
- edit something (doesn't reload)
- `npm i -S bankai@9.4.0`
- try again

I think it happened between 9.4.0 and 9.4.1, haven't looked deeper. 

Hope it's not something weird I did to my dev env. 

yours

**Comment by goto-bus-stop** [comment]
yep it's #392

**Comment by goto-bus-stop** [comment]
Live reload kicks in when the `documents:index.html` node updates; that node updates when `scripts:list` changes; `scripts:list` only changes if there was a change in dynamic bundles (from split-require). Maybe it should listen for both `scripts:bundle.js` and `scripts:list`, but then we'd get two reloads when you are using split-require 🤔

**Comment by goto-bus-stop** [comment]
#443 removes the `scripts:list` node and instead stores everything on `scripts:bundle.js`; so it should address this issue too!

**Comment by goto-bus-stop** [comment]
Appears to work again since #443 was merged!
