### ISSUE TITLE
Transforming dependencies with babelify breaks underscore.js

### ISSUE THREAD

**Issue by aknuds1** [choojs/bankai#423]
**Choose one:** This is a 🐛 bug report

## Expected Behavior

Building an app depending on underscore.js (directly or indirectly) should work, also the build should be reasonably quick.

## Current Behavior
Since bankai transforms dependencies with babelify, at least underscore.js as a dependency gets broken (due to global `this` becoming undefined instead of `window` or `global`). The build also gets slowed down significantly (for me 5-6 times).

## Possible Solution
Add option to enable or disable babelify on dependencies.

## Context
It breaks my underscore.js dependency and slows down my build 5-6x.

**Comment by goto-bus-stop** [comment]
#455 disables the Babel modules transform which solves most if not all of these cases. and #422 can be used if speed is an issue. thanks!
