### ISSUE TITLE
9.7.0 modify css file, bankai start does not watch 🐛

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/bankai#432]
9.6.1 is ok

## Code Sample
[bankai_issue_432](https://github.com/ZhouHansen/bankai_issue_432)

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | 9.7.0
| Runtime          | node 9.2.0
| Package Manager  | npm 5.6.0
| Operating System | osx

**Comment by goto-bus-stop** [comment]
Dang, this almost certainly must be because of the persistent cache…

**Comment by goto-bus-stop** [comment]
Mhmhm it looks like the persistent cache doesn't support emitting 'file' events from transforms. Guess we should revert that for now

**Comment by goto-bus-stop** [comment]
:package: 9.7.2
