### ISSUE TITLE
_fs is not defined and sourcemaps

### ISSUE THREAD

**Issue by dpaez** [choojs/bankai#449]
**Choose one:** this a 🐛 bug report

Hi 👋choo fan here 👍 😄 

I'm having an issue running an app created using `create-choo-app`. I've created a [repo](https://github.com/dpaez/choo-issue-demo) which helps to reproduce the issue I'm having (more info on the repository's readme). In summary, it seems to be related with sourcemaps and the transformations done by browserify (bankai setup), specifically the global `brfs`. But, honestly, I'm not sure, so any hint is welcome. Also, it's highly probable that this not an issue at all, or at least a bankai issue. 

## Expected Behavior

`bankai start` and `bankai build` should work as expected, ie, starting a development server ok and creating {js|css} valid bundles. 

For example, on one of  my [projects](https://github.com/dpaez/async-tour) I'm using sheetify as dependency. Sheetify uses postcss which includes sourcemaps inside every file. One of these files is using the fs module along with ES6 `imports`. I think there is some relation between this issue and how sourcemaps are parsed by bankai.

## Current Behavior

Now, when I ran `bankai start` or `bankai build` there is an error in the console but the start and build tasks can continue. The result is a broken js bundle, which logs an `_fs is not defined` error. 

Error:
`...bundle tried to statically call { readFileSync: [Function: readFileSync], readFile: [Function: readFile], readdirSync: [Function: readdirSync], readdir: [Function: readdir] } as a function`

## Possible Solution

I've played a bit with the browserify options, with the [async-tour project](https://github.com/dpaez/async-tour) I've been able to avoid this issue by disabling the brfs global transformation, but I'm not sure this is something desired.

## Context

The original problem was detected after update bankai to latest 9.x version on the [async-tour](https://github.com/dpaez/async-tour) project. It works ok with bankai 8.x (but that version creates a simpler bundle).

## Code Sample

[This repo](https://github.com/dpaez/choo-issue-demo) can help to reproduce the problem.

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | bankai 9.x |
| Runtime          | node 8.x |
| Package Manager  | npm 5.x |
| Operating System |  MacOS |

**Comment by goto-bus-stop** [comment]
static-module (and thus brfs) doesn't work with transpiled ES modules. Babel adds a wrapper around the require() calls that static-module doesn't know what to do with. Using `require('fs')` should work as a workaround.

**Comment by dpaez** [comment]
Hi @goto-bus-stop Thanks for taking some time on this issue. :smile_cat: 

I have the following use case: one choo lib X is requiring sheetify and then this lib X is being used by another choo app, with `app.use(...)`. 
sheetify is using postcss, which is using es6 modules, they are [transpiling with babel](https://github.com/postcss/postcss/blob/master/gulpfile.js#L12). So in this scenario I can not control the module and use `require` instead of `import`.

Do you have any suggestion for a situation like this?

Thanks in advance! :+1:

**Comment by goto-bus-stop** [comment]
Ah; sheetify itself should not end up in a browser bundle. Maybe we should make it a `global` transform too :/ It would be best if the dependency could somehow transform sheetify to insert-css() calls before publishing but that is tricky right now.

**Comment by dpaez** [comment]
That sounds right :cool:

**Comment by dpaez** [comment]
I'm back! :smile: 

I've just tried applying the global sheetify transform (modifying my local copy of bankai) and it works like a charm!

I can make a PR if it is something that the choo team would consider to be useful. 

Thanks for your help @goto-bus-stop !

**Comment by goto-bus-stop** [comment]
Oh actually a better approach might be to add the sheetify transform to the dependency's package.json:

```js
"dependencies": {
  "sheetify": "^7.3.0"
},
"browserify": {
  "transforms": ["sheetify"]
}
```

That way we don't have to add another global transform to bankai, and users of your module that just use the browserify CLI will not need to do anything special for your module to work correctly.

**Comment by dpaez** [comment]
Unfortunately this doesn't work for me. I'm getting the same error: 
```
browserify.bundle tried to statically call { readFileSync: [Function: readFileSync], readFile: [Function: readFile], readdirSync: [Function: readdirSync], readdir: [Function: readdir] } as a function while parsing file: /somepath/choo-slides/node_modules/postcss/lib/previous-map.js
```

The scenario was like the following:

module A -- is consuming ---> module B (this where I'm applying the transform) --> sheetify ---> postcss

[`A`](https://github.com/dpaez/async-tour) was created using `create-choo-app`. Nothing changed here.
 
In [`B`](https://github.com/geut/choo-slides) I added the browserify transform at package.json level. In the same way you mentioned above (also tried adding a plugin option, since [I was originally using css-extract](https://github.com/geut/choo-slides/blob/master/package.json#L9)).

__note: they are npm linked together.__

**Comment by dpaez** [comment]
You can omit my previous comment. I made a mistake, it was **transform** not *transforms* the actual key on the package.json. I've tried again and I can confirm it is working. So, I'm going back to fix my module and this issue can be closed. 

Thanks again @goto-bus-stop! 👏
