### ISSUE TITLE
Bankai crashes when Chrome loads webpage

### ISSUE THREAD

**Issue by louiscenter** [choojs/bankai#456]
Bankai is crashing when I initially load my choo app using Chrome. The error Bankai throws before crashing is the following:

```
Error: route '/favicon.ico' did not match.
```

This is *not* occurring on Firefox. 

## Expected Behavior

When Chrome initially loads a choo app, Bankai should gracefully handle `favicon.ico` 404ing.

## Current Behavior
Bankai crashes when Chrome requests `favicon.ico`.

## Possible Solution
I'm unsure how to resolve this issue, but I did notice this problem previously existed with Firefox. Here was a PR that resolved this last year: https://github.com/choojs/bankai/pull/218

## Your Environment
Node v8.9.0
Bankai v9.10.4

**Comment by akilism** [comment]
Just wanna leave a note that this is happening in Firefox nightly as well.

**Comment by goto-bus-stop** [comment]
:package: 9.10.5. Thanks!
