### ISSUE TITLE
components loaded via `split-require` are absent after `build`

### ISSUE THREAD

**Issue by amsross** [choojs/bankai#472]
this a 🐛 bug report

## Expected Behavior

Running `bankai start app.js` should build the file(s) `bundle-[#].js` for the lazily loaded asset.
Running `bankai build app.js` should build the file(s) `bundle-[#].js` for the lazily loaded asset.

## Current Behavior

The `bundle-[#].js` file(s) **are** accessible via HTTP requests after running `bankai start app.js`.
The `bundle-[#].js` file(s) **are not** present in `dist` after running `bankai build app.js`

There is no error.

## Context
It's obviously possible this is more related to `split-require` than `bankai`, but the fact that `bankai start app.js` works while `bankai build app.js` does not makes me think otherwise.

## Code Sample
I am able to reproduce this with my code as well as the sample code from https://github.com/goto-bus-stop/split-require#what

`package.json`
```
{
  "scripts": {
    "build": "bankai build app.js",
    "start": "bankai start app.js"
  },
  "dependencies": {
    "choo": "6.10.3"
  },
  "devDependencies": {
    "bankai": "9.11.1",
    "split-require": "3.1.0"
  }
}
```

`app.js`
```
var html = require('choo/html')
var app = require('choo')()
var splitRequire = require('split-require')

app.route('/', mainView)
app.mount('body')

var component
function mainView () {
  return html`<body>
    <h1>Loading</h1>
  </body>`
}

splitRequire('split-require', function (err, exports) {
  console.log(err, exports)
  app.emitter.emit('render')
})
```

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | bankai@9.11.1, split-require@3.1.0
| Runtime          | node@8.9.4, node@6.14.1
| Package Manager  | npm@5.8.0, npm@3.10.10
| Operating System | macOS 10.13.04

**Comment by amsross** [comment]
The following versions appear to work together:
```
➜ npm list split-require bankai
├─┬ bankai@9.1.0
│ └── split-require@2.0.3  deduped
└── split-require@2.0.3
```

**Comment by goto-bus-stop** [comment]
:package: 9.11.2 should fix this. thanks!
