### ISSUE TITLE
🔦Where would bankai check for favicon.ico?

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/bankai#490]
This is a 🔦question

Adding favicon is a todo task. So where would bankai check for favicon.ico, `assets/`, root directory or both?

**Comment by goto-bus-stop** [comment]
Hmmm :thinking: I think the root directory would be best, because `assets/` is served as `mywebsite.net/assets` and the favicon should probably be at `mywebsite.net/favicon.ico` instead.

**Comment by ZhouHansen** [comment]
Thanks for your suggestion.
