### ISSUE TITLE
🔦 compiler.assets() seems useless?

### ISSUE THREAD

**Issue by ZhouHansen** [choojs/bankai#491]
This is a 🔦question.

On `bankai build` run, `fs.copyFile()` deals with the assets. On `bankai start` run, we use compiler.assets() only to [check whether the asset file exists](https://github.com/choojs/bankai/blob/master/http.js#L64-L70), which can be replaced by

```js
send(req, name)
  .on('error', function (err) {
    res.statusCode = 404
    return res.end(err.message)
  })
  .pipe(res)
```

How about removing the compiler.assets()?

**Comment by goto-bus-stop** [comment]
`compiler.assets()` also returns the full file path. I think that's a useful abstraction, then `bankai start` doesn't have to `path.join` anything manually.
