### ISSUE TITLE
🐛Multiple external css files not built on build but ok on start

### ISSUE THREAD

**Issue by yudao** [choojs/bankai#495]
🐛 bug report

## Expected Behavior

All CSS local files compiled into bundle.css on build.

## Current Behavior

Only the first css file is compiled on build. Even if I change the order.
But it's ok when start is running.

## Code Sample
```js
var choo = require('choo')
var css = require('sheetify')

var MainView = require('./views/main')

css('tachyons') // <= COMPILED
css('./tachyons.extend.css')  // <= NOT COMPILED
css('./fonts.css')  // <= NOT COMPILED

const app = choo()
if (process.env.NODE_ENV !== 'production') {
  app.use(require('choo-devtools')())
  app.use(require('choo-service-worker/clear')())
}
app.use(require('choo-service-worker')())
app.route('/', MainView)
app.mount('body')
```

## Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| Package          | 9.12.1
| Runtime          | node 8.9.4
| Package Manager  | npm 6.1.0
| Operating System | Mac OSX High Sierra 10.13.4

**Comment by ZhouHansen** [comment]
Can't reproduce, try it: [bankai-issue-495](https://github.com/ZhouHansen/bankai-issue-495)

**Comment by yudao** [comment]
I've found the problem! 
I've let an @import directive in my tachyons.extend.css:
```css
@import url(https://fonts.googleapis.com/css?family=Work+Sans:300,400,500,600,700&amp;lang=en);
```
It breaks the build.
